### ISSUE TITLE
게시판의 개설 방법 논의

### ISSUE THREAD

**Issue by hig4342** [osamhack2021/WEB_Millage_ICM#15]
## 개요
밀리지 프로젝트는 부대 별 독립적 커뮤니티 구축을 목표로 하고 있습니다. 이에 관련하여 게시판의 개설 방법을 저희 개발자들이 아닌 해당 부대의 관리자에게 맡기는 것이 더 좋아보입니다.
실제 운영중인 에브리타임의 경우 게시판이 자유롭게 추가될 수 있습니다. 해당 기능을 참고하여 고정된 게시판이 아니라 부대 자체적으로 게시판을 생성할 수 있으며 게시판을 생성하는건 관리자가 할 수 있었으면 좋겠습니다.

## Todos
- [ ] 게시판 제목
- [ ] 게시판 부제목(게시판의 특징)
  - ex) 5감사 게시판 - 부대 내에서 장병에게 고마운 일을 적는 게시판입니다.
- [ ] 작성 권한
- [ ] 볼수있는 권한
- [ ] 작성자 공개 여부 등
- [ ] 글 작성/편집 에디터 선정 ([WYSIWYG 에디터](https://ko.wikipedia.org/wiki/%EC%9C%84%EC%A7%80%EC%9C%84%EA%B7%B8))

## 논의 내용
1. 게시판의 개설을 자유롭게 만들 것인지 정해진 게시판만 있는지 논의
2. 게시판의 개설이 자유롭다면 개설할 때 선택할 수 있는 기능 논의
3. 일반 게시판이 아닌 특수 목적을 가진 게시판(부대 메인화면에서 보여지는 공지사항 게시판 등)도 추가 기능으로 고를 수 있게 하는지 혹은 기본적으로 몇몇 게시판은 만들어 놔야하는지 논의

**Comment by thn02046** [comment]
1. 기본 기능(필수 선택)
2. 기본적으로 제공하되 선택가능한 기능
3. 부대별 커스터마이징

이렇게 3가지 옵션이 있다고 생각합니다. 부대마다 각자의 상황에 맞는 기능을 커뮤니티에 구현하고자 한다면 3의 요소가 필수적이라는데 동의합니다. 하지만 여타의 커뮤니티 서비스와의 차별점을 갖기 위해서, 또 초기 단계에 우리 사이트에 꾸준히 접속하는 유저들을 확보하기 위해서는 모든 부대에서 보편적으로 추구할만한 가치들을 1, 2의 형태로 제공하는것이 좋다고 생각합니다. 또 필수적으로 1에 해당하는 요소들이 필요하다고 생각합니다.(에타에 시간표, 강의평가 등 기본적으로 주어지는 기능들이 있는것 처럼)
'독립적인'이라는 가치가 각자의 기호에 맞는 환경을 구성할수 있다는 점에서 매력적이지만 독립성에만 포커스를 맞추다 보면 사용자의 접근성이 떨어질 수 있다고 생각합니다. 또 군대라는 동일한 환경 내에서 모든 부대가 좋아할만한 기능이 존재할것입니다. 독립성을 보장해줌과 동시에 각 부대에서 여태껏 생각지 못했던 기능을 기본적으로 제공하여 새로운 사용자 경험을 창출하는것이 가장 좋다고 생각합니다.

요약하자면 저는 차별화, 사용자들의 쉬운 접근을 위해서 기본으로 주어지는 기능이 있고 부가적으로 관리자가 원하는 기능을 추가로 구현할 수 있다는 의미에서 독립적인 커뮤니티가 되는것이 가장 이상적이라고 생각합니다.

**Comment by nailerHeum** [comment]
저는 이 서비스가 주로 모바일 환경에서 사용될 것으로 생각합니다. 네이버 블로그의 경우 wysiwyg 에디터가 제공되지만 에브리타임과 블라인드의 경우 글을 작성하고, 사진들을 첨부하는 기능만 사용할 수 있습니다. 두 방식이 장단점이 있는 만큼 논의를 해보면 좋을 것 같습니다.

**Comment by pec9399** [comment]
@thn02046 현재 기능들을 구현하는데 있어서 게시판에 에디터가 꼭 필요할까요?
