### ISSUE TITLE
[Board] 남은 업무

### ISSUE THREAD

**Issue by bwmelon97** [osamhack2021/WEB_Millage_ICM#373]
### 기능
- [x] 게시글 페이지 - Comment 기능 -> #414 #451 
- [x] 게시글 페이지 - 쪽지 기능 (console에 id 나오는 기능까지만 구현) -> #384 
- [x] Side Component -> #451 
- [x] 게시판 관리 페이지 -> #400

### Backend API 연결
- [x] Create Board API 연결
- [x] Create Post API 연결

### 스타일링
-  Main Page 스타일링 ( PostItem / 부대사진 이미지 )
    - [x] PostItem
    - [x] 부대사진
- [x] 게시판 생성 페이지
- [x] 게시글 생성 페이지
- [x] 게시판 페이지
- [x] 게시글 페이지

**Comment by pec9399** [comment]
전체 페이지
![image](https://user-images.githubusercontent.com/31975515/137420027-b5c78e10-3e47-494e-b68c-bef1e7b97bf7.png)

추가 Dialog
![image](https://user-images.githubusercontent.com/31975515/137420051-2fadcf51-605e-46cd-af5e-5ae5b32a5b6a.png)
