### ISSUE TITLE
[README] README 페이지 Todo list

### ISSUE THREAD

**Issue by eunchan-park** [osamhack2021/WEB_Millage_ICM#498]
README 페이지를 꾸미기 위하여 필요한 내용들입니다.

[README 위키 페이지](https://github.com/osamhack2021/WEB_Millage_ICM/wiki/README.md)

시간 남는대로 이 페이지에서 어떤거 하고 계신지 올려주시고 디자인이 어려우시면 디자인을 제외한 내용만 채워주세요!

- [x] 로고 및 데모페이지, docs, contributing 등 주요 문서로 이동하는 버튼
- [x] 시연 영상 링크
- [x] 팀 소개
- [x] 프로젝트 소개 꾸미기 + 내용 보완 
- [x] 기능 설계, 모바일 지원 내용
- [x] 서비스 플로우 (현재 기능에 맞게 수정 필요)
- [x] DB Schema ERD
- [x] 기대효과 꾸미기 + 내용보완
- [x] 경쟁력 
- [x] 컴퓨터 구성 / 필수 조건 안내 (테이블로 하면 좋을 것 같습니다)
- [x] 기술 스택
- [x] 서비스 이용 방법
- [x] 개발 프로젝트 사용 방법
- [x] 팀 정보 / 역할
